USE [master]
GO

/****** Object:  Database [HVTClubDB]    Script Date: 05-Nov-17 07:39:22 PM ******/
CREATE DATABASE [HVTClubDB]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'HVTClubDB', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL12.SQLEXPRESS\MSSQL\DATA\HVTClubDB.mdf' , SIZE = 4096KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'HVTClubDB_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL12.SQLEXPRESS\MSSQL\DATA\HVTClubDB_log.ldf' , SIZE = 1024KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO

ALTER DATABASE [HVTClubDB] SET COMPATIBILITY_LEVEL = 120
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [HVTClubDB].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [HVTClubDB] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [HVTClubDB] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [HVTClubDB] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [HVTClubDB] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [HVTClubDB] SET ARITHABORT OFF 
GO

ALTER DATABASE [HVTClubDB] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [HVTClubDB] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [HVTClubDB] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [HVTClubDB] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [HVTClubDB] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [HVTClubDB] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [HVTClubDB] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [HVTClubDB] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [HVTClubDB] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [HVTClubDB] SET  DISABLE_BROKER 
GO

ALTER DATABASE [HVTClubDB] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [HVTClubDB] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [HVTClubDB] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [HVTClubDB] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [HVTClubDB] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [HVTClubDB] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [HVTClubDB] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [HVTClubDB] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [HVTClubDB] SET  MULTI_USER 
GO

ALTER DATABASE [HVTClubDB] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [HVTClubDB] SET DB_CHAINING OFF 
GO

ALTER DATABASE [HVTClubDB] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [HVTClubDB] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO

ALTER DATABASE [HVTClubDB] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [HVTClubDB] SET  READ_WRITE 
GO


